logging:
  level:
    io:
      spring:
        cloud:
          samples: DEBUG
configuration:
  projectName: config-client
fortune:
  fallbackFortune: The fog should lift today.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
